export const questions = [
  { id: "q1", text: "I feel nervous or unsure of my ability to stay sober." },
  { id: "q2", text: "I have many problems in my life." },
  { id: "q3", text: "I tend to overreact or act impulsively." },
  { id: "q4", text: "I keep to myself and feel lonely." },
  { id: "q5", text: "I get too focused on one area of my life." },
  { id: "q6", text: "I feel blue, down, listless, or depressed." },
  { id: "q7", text: "I engage in wishful thinking." },
  { id: "q8", text: "The plans that I make succeed." },
  {
    id: "q9",
    text: "I have trouble concentrating and prefer to dream about how things could be.",
  },
  { id: "q10", text: "Things don’t work out well for me." },
  { id: "q11", text: "I feel confused." },
  { id: "q12", text: "I get irritated or annoyed with my friends." },
  { id: "q13", text: "I feel angry or frustrated." },
  { id: "q14", text: "I have good eating habits." },
  { id: "q15", text: "I feel trapped and stuck, like there is no way out." },
  { id: "q16", text: "I have trouble sleeping." },
  { id: "q17", text: "I have long periods of serious depression." },
  { id: "q18", text: "I don’t really care what happens." },
  {
    id: "q19",
    text: "I feel like things are so bad that I might as well drink.",
  },
  { id: "q20", text: "I am able to think clearly." },
  { id: "q21", text: "I feel sorry for myself." },
  { id: "q22", text: "I think about drinking." },
  { id: "q23", text: "I lie to other people." },
  { id: "q24", text: "I feel hopeful and confident." },
  { id: "q25", text: "I feel angry at the world in general." },
  { id: "q26", text: "I am doing things to stay sober." },
  { id: "q27", text: "I am afraid that I am losing my mind." },
  { id: "q28", text: "I am drinking out of control." },
];
